"""Agregar cierre_forzado y fecha_cierre_notas

Revision ID: 986ca44a6c85
Revises: e50b436349b7
Create Date: 2026-05-22 22:33:26.632669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '986ca44a6c85'
down_revision = 'e50b436349b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodos_academicos', schema=None) as batch_op:
        batch_op.drop_column('fecha_autorizacion')
        batch_op.drop_column('autorizado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodos_academicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autorizado_por', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_autorizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
